run:
  deadline: 3m

  build-tags:
    - selinux
    - seccomp

linters:
  enable-all: true
  disable:
    - depguard
    - gochecknoglobals
    - gochecknoinits
    - prealloc
    - wrapcheck
    - varnamelen
    - errcheck
    - nonamedreturns
    - ireturn
    - exhaustruct
    - tagliatelle
    - goimports
    - exhaustive
    - tagalign
    - lll
    - gofumpt
    - gci
    - funlen
    - godot
    - cyclop
    - forcetypeassert
    - gomnd
    - execinquery

linters-settings:
  govet:
    settings:
      printf:
        funcs:
          - (github.com/golang/glog.Verbose).Infof
          - github.com/golang/glog.Infof
          - github.com/golang/glog.Warningf
          - github.com/golang/glog.Errorf
          - github.com/golang/glog.Fatalf
          - github.com/golang/glog.Exitf
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 20

  lll:
    tab-width: 4
  prealloc:
    simple: true


issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec
        - lll
        - scopelint

    - path: pkg/server/runtime/streaming.go
      linters:
        - gocyclo

    - text: "vendor/github.com/kubernetes-sigs/cri-o/pkg/seccomp/seccomp.go"
      linters:
        - typecheck

    - path: pkg/server
      linters:
        - lll

  max-issues-per-linter: 0
  max-same-issues: 0

service:
  prepare:
    - apt-get update
    - apt-get install -y libseccomp-dev