version: "3.9"

services:
    postgres:
      image: postgres:16.2-alpine
      container_name: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123456
        - POSTGRES_DB=authDB
      volumes:
        - ./postgres/data:/var/lib/postgresql/data
    auth:
      depends_on:
        - postgres
      build:
        context: .
        dockerfile: ./Dockerfile
      container_name: auth
      restart: unless-stopped
      ports:
        - 22001:22000
