version: "3.9"

services:
    postgres:
      image: postgres:16.2-alpine
      container_name: postgres
      restart: on-failure
      env_file: .env
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
      volumes:
        - ./postgres-auth/data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - auth_network

    auth:
      image: auth
      build:
        context: .
        dockerfile: ./Dockerfile
      container_name: auth
      env_file:
        - .env
      environment:
        - POSTGRES_PASSWORD=${DB_PASSWORD}
      restart: on-failure
      ports:
        - "22000:22000"
      depends_on:
        - postgres
      networks:
        - auth_network

networks:
  auth_network:
    driver: bridge