version: "3.9"

services:
  auth:
    env_file:
      - .env.prod
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      resources:
        limits:
          memory: '512M'
          cpus: '0.5'

  postgres:
    env_file: .env.prod