version: "3.9"

services:
   auth:
    image: your-registry/auth
    container_name: auth
    env_file:
      - .env
    environment:
      - PGSQL_PASSWORD=${DB_PASSWORD}
    restart: on-failure
    ports:
      - "5000:22000"
      - "8085:8081"
    depends_on:
      - postgres
    volumes:
      - ./configs:/app/configs
    networks:
      - network

   postgres:
     image: postgres:16.2-alpine
     restart: on-failure
     env_file: .env
     environment:
       - POSTGRES_USER=${DB_USER}
       - POSTGRES_PASSWORD=${DB_PASSWORD}
       - POSTGRES_DB=${DB_NAME}
     volumes:
       - ./postgres-auth-data:/var/lib/postgresql/data
     ports:
       - "5500:5432"
     networks:
       - network
     healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  network:
    driver: bridge