grpc:
  port: 22000
  timeout: 5000

logging:
  mode: "dev"

jwt:
  expire_access: "2h"
  expire_refresh: "105h"

postgres:
  host: "postgres:5432"
  user: "postgres"
  dbname: "authDB"
  sslmode: "disable"
  max_conns: 15
  max_idle_conns: 15
  max_conn_lifetime: "2h"